// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 05/06/2026 11:07:57
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/loris/Documents/TANA/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/loris/Documents/TANA/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/loris/Documents/TANA/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/loris/Documents/TANA/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/loris/Documents/TANA/plugins/**/*.{js,ts,mjs}","/home/loris/Documents/TANA/composables/**/*.{js,ts,mjs}","/home/loris/Documents/TANA/utils/**/*.{js,ts,mjs}","/home/loris/Documents/TANA/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/loris/Documents/TANA/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/loris/Documents/TANA/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/loris/Documents/TANA/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;